// Step IDs enum - matching frontend
export enum StepId {
  // Initial state
  IDLE = "IDLE",
  
  // Part -1: Variable Identification
  P_NEG1_1_VARIABLE_IDENTIFICATION = "P_NEG1_1_VARIABLE_IDENTIFICATION",
  
  // Part 0: Data Preparation
  P0_1_TRANSCRIPTION_ADHERENCE = "P0_1_TRANSCRIPTION_ADHERENCE",
  P0_2_REFINE_DATA_TYPES = "P0_2_REFINE_DATA_TYPES",
  P0_3_SELECT_PROCEDURAL_UTTERANCES = "P0_3_SELECT_PROCEDURAL_UTTERANCES",
  
  // Part I: Specific Diachronic Analysis
  P1_1_INITIAL_SEGMENTATION = "P1_1_INITIAL_SEGMENTATION",
  P1_2_DIACHRONIC_UNIT_ID = "P1_2_DIACHRONIC_UNIT_ID",
  P1_3_REFINE_DIACHRONIC_UNITS = "P1_3_REFINE_DIACHRONIC_UNITS",
  P1_4_CONSTRUCT_SPECIFIC_DIACHRONIC_STRUCTURE = "P1_4_CONSTRUCT_SPECIFIC_DIACHRONIC_STRUCTURE",
  
  // Part II_S: Specific Synchronic Analysis
  P2S_1_GROUP_UTTERANCES_BY_TOPIC = "P2S_1_GROUP_UTTERANCES_BY_TOPIC",
  P2S_2_IDENTIFY_SPECIFIC_SYNCHRONIC_UNITS = "P2S_2_IDENTIFY_SPECIFIC_SYNCHRONIC_UNITS",
  P2S_3_DEFINE_SPECIFIC_SYNCHRONIC_STRUCTURE = "P2S_3_DEFINE_SPECIFIC_SYNCHRONIC_STRUCTURE",
  
  // Part III: Generic Diachronic Analysis
  P3_1_ALIGN_STRUCTURES = "P3_1_ALIGN_STRUCTURES",
  P3_2_IDENTIFY_GDUS = "P3_2_IDENTIFY_GDUS",
  P3_3_DEFINE_GENERIC_DIACHRONIC_STRUCTURE = "P3_3_DEFINE_GENERIC_DIACHRONIC_STRUCTURE",
  
  // Part IV_S: Generic Synchronic Analysis
  P4S_1_A_IDENTIFY_AND_GROUP_SSS_NODES = "P4S_1_A_IDENTIFY_AND_GROUP_SSS_NODES",
  P4S_1_B_DEFINE_GSS_FROM_GROUPS = "P4S_1_B_DEFINE_GSS_FROM_GROUPS",
  
  // Part V: Refinement
  P5_1_IV_COMPARATIVE_ANALYSIS = "P5_1_IV_COMPARATIVE_ANALYSIS",
  P5_2_HOLISTIC_REFINEMENT = "P5_2_HOLISTIC_REFINEMENT",
  
  // Part VII: Causal Modeling
  P7_1_CANDIDATE_VARIABLE_FORMALIZATION = "P7_1_CANDIDATE_VARIABLE_FORMALIZATION",
  P7_2_PROPOSE_PAIRWISE_CAUSAL_LINKS = "P7_2_PROPOSE_PAIRWISE_CAUSAL_LINKS",
  P7_3_ASSEMBLE_DAG_AND_IDENTIFY_PATTERNS = "P7_3_ASSEMBLE_DAG_AND_IDENTIFY_PATTERNS",
  P7_3B_VALIDATE_AND_CLEAN_DAG = "P7_3B_VALIDATE_AND_CLEAN_DAG",
  P7_4_ANALYZE_PATHS_AND_BIASES = "P7_4_ANALYZE_PATHS_AND_BIASES",
  P7_5_GENERATE_FORMAL_HYPOTHESES = "P7_5_GENERATE_FORMAL_HYPOTHESES",
  
  // Part VI: Report Generation
  P6_1_GENERATE_MARKDOWN_REPORT = "P6_1_GENERATE_MARKDOWN_REPORT",
  
  // Part IX: Inter-Rater Reliability Analysis
  P9_1_SEMANTIC_GDU_MAPPING = "P9_1_SEMANTIC_GDU_MAPPING",
  
  // Final state
  COMPLETE = "COMPLETE"
}