/**
 * P3_3 Define Generic Diachronic Structure - Prompt Generation
 * EXACT COPY of working prototype's prompt template
 */

import { GeneratePromptFunction } from '../../core/interfaces';
import { P3_3_Input } from './types';

/**
 * Generate prompt for P3_3 step
 * EXACT COPY of working prototype's generatePrompt template
 */
export const generatePrompt: GeneratePromptFunction = (inputData: P3_3_Input): string => {
  // EXACT prompt template from the working prototype
  return `You are a Generic Diachronic Analysis assistant. Task: Define the Generic Diachronic Structure (GDS) using GDUs and IV insights.
Input:
- P3.1 output (\`aligned_structures_report\`, etc.).
- P3.2 output (\`identified_gdus\`, where each GDU has a \`gdu_id\`).
- Global DV focus.
${JSON.stringify(inputData, null, 2)}

Instructions:
1.  Construct GDS: Based on \`aligned_structures_report\` (from P3.1) and \`identified_gdus\` (from P3.2), define the GDS. This includes:
    *   \`name\`: A descriptive name for the GDS.
    *   \`description\`: An overall description of the GDS.
    *   \`core_gdus\`: An array of \`gdu_id\` strings (from P3.2 input) that are essential to this GDS.
    *   \`optional_gdus\` (Optional): An array of \`gdu_id\` strings that may appear.
    *   \`typical_sequence\` (Optional): An array of \`gdu_id\` strings representing a common temporal order.
2.  Summarize IV Variants: Explain how the GDS might vary based on different IVs, drawing from previous IV notes in P3.1 and P3.2.
3.  Confidence: State your confidence (e.g., "High", "Medium", "Low") in the defined GDS.

Output:
A JSON object adhering EXACTLY to the following structure:
{
  "generic_diachronic_structure_definition": {
    "name": "GDS Name",
    "description": "Overall GDS description.",
    "core_gdus": ["GDU_Core1_id", "GDU_Core2_id"],
    "optional_gdus": ["GDU_Optional1_id"],
    "typical_sequence": ["GDU_Core1_id", "GDU_Optional1_id", "GDU_Core2_id"]
  },
  "variants_summary": "Summary of GDS variants based on IVs.",
  "confidence_level": "High/Medium/Low",
  "dependent_variable_focus": ${JSON.stringify(inputData.global_dv_focus)}
}
Do NOT include a "mermaid_syntax_generic_diachronic" field; this will be generated by the system later.`;
};