/**
 * P3_3 Define Generic Diachronic Structure - Output Parsing
 * Exactly matches the working prototype's parseOutput behavior
 */

import { ParseOutputFunction } from '../../core/interfaces';
import { P3_3_Output, GenericDiachronicStructureDefinition } from './types';

/**
 * Parse and validate output for P3_3 step
 * Exactly matches the working prototype's parsing logic
 */
export const parseOutput: ParseOutputFunction = (rawOutput: any): P3_3_Output => {
  console.log(`[P3_3 parseOutput] Parsing raw output:`, rawOutput);

  // Validation: Check required fields (matches prototype validation)
  if (!rawOutput.generic_diachronic_structure_definition) {
    throw new Error('P3_3 output missing required field: generic_diachronic_structure_definition');
  }

  if (!rawOutput.variants_summary) {
    throw new Error('P3_3 output missing required field: variants_summary');
  }

  if (!Array.isArray(rawOutput.dependent_variable_focus)) {
    throw new Error('P3_3 output field dependent_variable_focus must be an array');
  }

  // Validate GDS definition structure (matches prototype GDS validation)
  const gdsDefinition = rawOutput.generic_diachronic_structure_definition;

  if (!gdsDefinition.name) {
    throw new Error('P3_3 generic_diachronic_structure_definition missing required field: name');
  }

  if (!gdsDefinition.description) {
    throw new Error('P3_3 generic_diachronic_structure_definition missing required field: description');
  }

  if (!Array.isArray(gdsDefinition.core_gdus)) {
    throw new Error('P3_3 generic_diachronic_structure_definition field core_gdus must be an array');
  }

  if (gdsDefinition.core_gdus.length === 0) {
    throw new Error('P3_3 generic_diachronic_structure_definition core_gdus cannot be empty');
  }

  // Validate optional fields if present
  if (gdsDefinition.optional_gdus && !Array.isArray(gdsDefinition.optional_gdus)) {
    throw new Error('P3_3 generic_diachronic_structure_definition field optional_gdus must be an array if present');
  }

  if (gdsDefinition.typical_sequence && !Array.isArray(gdsDefinition.typical_sequence)) {
    throw new Error('P3_3 generic_diachronic_structure_definition field typical_sequence must be an array if present');
  }

  // Create validated GDS definition (matches prototype structure)
  const validatedGdsDefinition: GenericDiachronicStructureDefinition = {
    name: gdsDefinition.name,
    description: gdsDefinition.description,
    core_gdus: gdsDefinition.core_gdus,
  };

  // Include optional fields if present
  if (gdsDefinition.optional_gdus) {
    validatedGdsDefinition.optional_gdus = gdsDefinition.optional_gdus;
  }

  if (gdsDefinition.typical_sequence) {
    validatedGdsDefinition.typical_sequence = gdsDefinition.typical_sequence;
  }

  // Return validated and structured output (matches prototype structure)
  const validatedOutput: P3_3_Output = {
    generic_diachronic_structure_definition: validatedGdsDefinition,
    variants_summary: rawOutput.variants_summary,
    dependent_variable_focus: rawOutput.dependent_variable_focus,
  };

  // Include optional confidence_level if present
  if (rawOutput.confidence_level) {
    validatedOutput.confidence_level = rawOutput.confidence_level;
  }

  // Note: mermaid_syntax_generic_diachronic is explicitly NOT included here
  // as per prototype - it's generated by the system later

  console.log(`[P3_3 parseOutput] Successfully validated output with GDS containing ${validatedGdsDefinition.core_gdus.length} core GDUs`);

  return validatedOutput;
};