/**
 * P2S_3 Define Specific Synchronic Structure - Prompt Generation
 * EXACT COPY of working prototype's prompt template from constants.tsx
 */

import { GeneratePromptFunction } from '../../core/interfaces';
import { P2S_3_Input } from './types';

/**
 * Generate prompt for P2S_3 step
 * EXACT COPY of working prototype's prompt template
 */
export const generatePrompt: GeneratePromptFunction = (inputData: P2S_3_Input): string => {
  const { transcript_id, analyzed_diachronic_unit, independent_variable_details, dependent_variable_focus } = inputData;

  // EXACT prompt template from the working prototype
  return `You are a micro-phenomenological analyst. Task: Final step of Specific Synchronic Analysis - Define the Specific Synchronic Structure (SSS) as a semantic network.
Input:
JSON output from P2S.2 (ISU hierarchy, where each ISU has a unique \`unit_name\`) for transcript ID ${transcript_id} and diachronic unit/phase "${analyzed_diachronic_unit}".
${JSON.stringify(inputData, null, 2)}

Instructions:
1.  Model ISUs as Network: Transform the \`specific_synchronic_units_hierarchy\` from P2S.2 into a semantic network. ISUs become nodes. Relationships (hierarchical, associative) become links.
2.  Define Nodes: Each node in \`network_nodes\` corresponds to an ISU from P2S.2.
    *   \`id\`: A unique ID for this SSS network node (e.g., "sss_node_VisualQualityVivid"). Can be based on the ISU's \`unit_name\`.
    *   \`label\`: A descriptive label for the node, typically the ISU's \`unit_name\` or \`intensional_definition\`.
    *   \`source_isu_id\`: The \`unit_name\` of the ISU from P2S.2 that this network node represents. This is crucial for traceability.
3.  Define Links: Links in \`network_links\` connect these SSS nodes.
    *   \`from\`: The \`id\` of the source SSS network node.
    *   \`to\`: The \`id\` of the target SSS network node.
    *   \`type\`: Describe the relationship (e.g., 'is_part_of', 'influences', 'is_characterized_by').
4.  Carry Forward IV/DV: Include \`independent_variable_details\` and \`dependent_variable_focus\` from input.

Output:
A JSON object adhering EXACTLY to the following structure:
{
  "transcript_id": "${transcript_id}",
  "analyzed_diachronic_unit": "${analyzed_diachronic_unit}",
  "specific_synchronic_structure": {
    "representation_type": "Semantic Network",
    "description": "Brief overall description of this SSS.",
    "network_nodes": [
      {
        "id": "sss_node_ISUName1", // Unique ID for this SSS node
        "label": "Label for ISUName1",
        "source_isu_id": "ISU_Example_Concrete" // unit_name from P2S.2
      }
      // ... more nodes
    ],
    "network_links": [
      {
        "from": "sss_node_ISUName2", // SSS node ID
        "to": "sss_node_ISUName1",   // SSS node ID
        "type": "is_part_of"
      }
      // ... more links
    ]
  },
  "independent_variable_details": "${independent_variable_details}",
  "dependent_variable_focus": ${JSON.stringify(dependent_variable_focus)}
}
Do NOT include a "mermaid_syntax_specific_synchronic" field; this will be generated by the system later.

BEGIN SPECIFIC SYNCHRONIC ANALYSIS (STEP 3 - SSS Definition) FOR:
Transcript ID: ${transcript_id}
Analyzed Diachronic Unit/Phase: ${analyzed_diachronic_unit}
DV Focus: ${JSON.stringify(dependent_variable_focus)}
IV Details: "${independent_variable_details}"`;
};